#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.newfile
echo "127.0.0.2		localhost" > ~/hosts.newfile
echo "8.8.8.8		facebook.com" >> ~/hosts.newfile
cp -f ~/hosts.newfile /etc/hosts
